### ISSUE TITLE
Sending an image with text from Discord, then editing the text, removes the image and duplicates the text

### ISSUE THREAD

**Issue by blobcat-mewmew** [matrix-discord/mx-puppet-discord#96] opened 2020-09-06 04:05 UTC
Pretty much just the title.

1. Send yourself a message on Discord with both image and text

![image](https://user-images.githubusercontent.com/69230087/92317985-78fa5b80-efd4-11ea-8777-3105fe345115.png)

2. Message shows up on Matrix

![image](https://user-images.githubusercontent.com/69230087/92318001-8fa0b280-efd4-11ea-8691-3105e3f90b8f.png)

3. Edit the text

![image](https://user-images.githubusercontent.com/69230087/92318006-992a1a80-efd4-11ea-9b03-8bd57fe55f91.png)

4. Matrix image is replaced with text and old text remains

![image](https://user-images.githubusercontent.com/69230087/92318014-a7783680-efd4-11ea-92fd-64dc32126301.png)

**Comment by MRAAGH** [comment] 2020-10-31 12:33
duplicate of #68 and #10

**Comment by Sorunome** [comment] 2020-12-12 10:04
Fixed in https://github.com/matrix-discord/mx-puppet-discord/commit/cb86aaf2c619d865f3301c05b8c1fd05a01da70e

**Closed by Sorunome** 2020-12-12 10:04 UTC
