### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by kerneus** [matrix-discord/mx-puppet-discord#203] opened 2022-03-09 12:28 UTC
my installation log:
https://pastebin.com/pNDrHtPH
npm --version
6.14.16
node --version
v14.19.0

**Comment by dsonck92** [comment] 2022-03-18 11:03
Duplicate of #201: NPM < 8 is not supported as installer due to how it forces SSH on repos. This has been observed in https://github.com/matrix-discord/matrix-discord-parser/runs/5239492006, and fixed by upgrading to NPM 8 https://github.com/matrix-discord/matrix-discord-parser/pull/24/commits/27262e1cb6c860882e2fad8ee7ff14917dd72a31

**Closed by dsonck92** 2022-03-18 11:03 UTC
